/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE_API__opencog__agent_finder
#define __PYX_HAVE_API__opencog__agent_finder
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"

static struct opencog::requests_and_agents_t (*__pyx_api_f_7opencog_12agent_finder_load_req_agent_module)(std::string) = 0;
#define load_req_agent_module __pyx_api_f_7opencog_12agent_finder_load_req_agent_module
static PyObject *(*__pyx_api_f_7opencog_12agent_finder_instantiate_agent)(std::string, std::string, opencog::Agent *) = 0;
#define instantiate_agent __pyx_api_f_7opencog_12agent_finder_instantiate_agent
static std::string (*__pyx_api_f_7opencog_12agent_finder_run_agent)(PyObject *, opencog::AtomSpace *) = 0;
#define run_agent __pyx_api_f_7opencog_12agent_finder_run_agent
static PyObject *(*__pyx_api_f_7opencog_12agent_finder_instantiate_request)(std::string, std::string, opencog::Request *) = 0;
#define instantiate_request __pyx_api_f_7opencog_12agent_finder_instantiate_request
static std::string (*__pyx_api_f_7opencog_12agent_finder_run_request)(PyObject *, std::list<std::string> , opencog::AtomSpace *) = 0;
#define run_request __pyx_api_f_7opencog_12agent_finder_run_request
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
#if PY_VERSION_HEX >= 0x02070000
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
#else
    {const char *desc, *s1, *s2;
    desc = (const char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    s1 = desc; s2 = sig;
    while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
    if (*s1 != *s2) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    tmp.p = PyCObject_AsVoidPtr(cobj);}
#endif
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_opencog__agent_finder(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("opencog.agent_finder");
  if (!module) goto bad;
  if (__Pyx_ImportFunction(module, "load_req_agent_module", (void (**)(void))&__pyx_api_f_7opencog_12agent_finder_load_req_agent_module, "struct opencog::requests_and_agents_t (std::string)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "instantiate_agent", (void (**)(void))&__pyx_api_f_7opencog_12agent_finder_instantiate_agent, "PyObject *(std::string, std::string, opencog::Agent *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "run_agent", (void (**)(void))&__pyx_api_f_7opencog_12agent_finder_run_agent, "std::string (PyObject *, opencog::AtomSpace *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "instantiate_request", (void (**)(void))&__pyx_api_f_7opencog_12agent_finder_instantiate_request, "PyObject *(std::string, std::string, opencog::Request *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "run_request", (void (**)(void))&__pyx_api_f_7opencog_12agent_finder_run_request, "std::string (PyObject *, std::list<std::string> , opencog::AtomSpace *)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__opencog__agent_finder */
